name: Deploy Angular to Hetzner

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run biome (lint)
        run: npm run biome


  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t clinic_room_frontend:latest .

      - name: Tag Docker image
        run: |
          docker tag clinic_room_frontend:latest jogajuntoufs/clinic_room_frontend:latest

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push jogajuntoufs/clinic_room_frontend:latest

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Hetzner
        run: |
          sshpass -p "${{ secrets.HETZNER_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.HETZNER_HOST }} << 'EOF'
          set -e
          sudo docker stop clinic_room_frontend
          sudo docker rm clinic_room_frontend
          sudo docker rmi jogajuntoufs/clinic_room_frontend:latest
          sudo docker pull jogajuntoufs/clinic_room_frontend:latest
          sudo docker run -d --name clinic_room_frontend -p 80:80 jogajuntoufs/clinic_room_frontend:latest
          sudo docker update --restart unless-stopped clinic_room_frontend
          EOF
        shell: bash
